### ISSUE TITLE
Can't figure out if you can launch movies anywhere app directly to a movie

### ISSUE THREAD

**Issue by xxKeoxx** [mattgyver83/adbee#2]
Is there any way to launch an app lice movies anywhere directly to the launch page of the movie after movies anywhere starts?

**Comment by mattgyver83** [comment]
Put bluntly, no.  This requires knowing the specific app intent and some other information that needs to be launched to get to the "page" of the app after launch.  Originally I wanted to do something like this but it was a huge pain and ultimately was something I could live without and work around using ADBs key emulation.  This is mostly designed to open an app and emulate using a keyboard or other android keyevents to "navigate" to a predetermined place.  If you can achieve your goal that way it may be of value for you otherwise it may be a dead end.

I still use this script in my home automation system so its not dead but for the foreseeable future there won't be any improvements or updates to it as I just don't have the time to expend on it for uses beyond my own and still see that type of feature as overly cumbersome with minimal reward.
